#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
xrandr --output HDMI-0 --right-of DP-4 &
pgrep -x dunst > /dev/null || dunst &
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf3 &
$HOME/.config/polybar/launch.sh &
pgrep -x nm-applet && nm-applet &
lxpolkit & # Graphical authentication agent

if [[ ! $(pidof xfce-polkit) ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

nm-applet &
blueman-applet &

# background
feh --bg-scale ~/.config/wallpappers/monument.jpg &

bspc monitor HDMI-0 -d 6 7 8 9
bspc monitor DP-4 -d 1 2 3 4 5
#### MONITORS ####
for monitor in $(bspc query -M)
do
    #bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6' '7'
    ((name++))
    # set the workspaces on each monitor to 1-9
    #bspc monitor $monitor -d 1 2 3 4
    #polybar hidden when fullscreen for vlc, youtube, mpv ...
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_$monitor)
done




bspc config border_width			2
bspc config window_gap				2
bspc config top_padding						0
bspc config bottom_padding              	0
bspc config left_padding                  	0
bspc config right_padding                 	0


bspc config split_ratio          			0.50
bspc config single_monocle			false
bspc config borderless_monocle   			true
bspc config gapless_monocle      			true
bspc config focus_follows_pointer 			true

bspc config click_to_focus                	true
#### BSPWM coloring ####
# bspc config normal_border_color           	"#5e81ac"
# bspc config active_border_color	     	 	  "#1e1e1e"
# bspc config focused_border_color	      	"#5e81ac"
# bspc config presel_feedback_color	      	"#5e81ac"
# bspc config urgent_border_color 	      	"#dd2727"

bspc config focused_border_color	"#8AB4F8"
bspc config normal_border_color		"#3C3C3C"
bspc config active_border_color		"#5e81ac"
bspc config presel_feedback_color	"#8AB4F8"


xsetroot -cursor_name left_ptr &
