-- DP-1 workspaces (1–10)
hl.workspace_rule({ workspace = "1",  monitor = "DP-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "2",  monitor = "DP-1", persistent = true })
hl.workspace_rule({ workspace = "3",  monitor = "DP-1", persistent = true })
hl.workspace_rule({ workspace = "4",  monitor = "DP-1", persistent = true })
hl.workspace_rule({ workspace = "5",  monitor = "DP-1", persistent = true })
hl.workspace_rule({ workspace = "6",  monitor = "DP-1", persistent = true })
hl.workspace_rule({ workspace = "7",  monitor = "DP-1", persistent = true })
hl.workspace_rule({ workspace = "8",  monitor = "DP-1", persistent = true })
hl.workspace_rule({ workspace = "9",  monitor = "DP-1", persistent = true })
hl.workspace_rule({ workspace = "10", monitor = "DP-1", persistent = true })

-- HDMI-A-1 workspaces (11–22)
hl.workspace_rule({ workspace = "11", monitor = "HDMI-A-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "12", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "13", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "14", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "15", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "16", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "17", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "18", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "19", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "20", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "21", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "22", monitor = "HDMI-A-1", persistent = true })
