color0 #3c4947
color1 #ffb4ab
color2 #4adcca
color3 #9fd0c7
color4 #d6baff
color5 #4adcca
color6 #9fd0c7
color7 #dde4e1
color8 #859490
color9 #ffb4ab
color10 #4adcca
color11 #9fd0c7
color12 #d6baff
color13 #4adcca
color14 #9fd0c7
color15 #dde4e1

cursor                #dde4e1
cursor_text_color     #0e1513
background            #0e1513
foreground            #dde4e1
selection_foreground  #bbcac6
selection_background  #3c4947
active_border_color   #4adcca
inactive_border_color #3c4947
url_color             #4adcca

active_tab_foreground   #003731
active_tab_background   #4adcca
inactive_tab_foreground #bbcac6
inactive_tab_background #3c4947
cursor_trail_color      #bbcac6
